AWSTemplateFormatVersion: '2010-09-09'
Description: CloudFormation Template to deploy smartStructsAPI to an EC2 instance

Resources:
  MyInstanceProfile:
    Type: 'AWS::IAM::InstanceProfile'
    Properties:
      Roles:
        - Ref: MyRole

  MyRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: 'ec2.amazonaws.com'
            Action: 'sts:AssumeRole'
      Policies:
        - PolicyName: 'CloudWatchLogsPolicy'
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - 'logs:CreateLogGroup'
                  - 'logs:CreateLogStream'
                  - 'logs:PutLogEvents'
                Resource: '*'
  EC2Instance:
    Type: 'AWS::EC2::Instance'
    Properties:
      InstanceType: t2.micro
      KeyName: ss_OH_API
      ImageId: ami-06b21ccaeff8cd686 # Amazon Linux 2 AMI
      SecurityGroups:
        - !Ref InstanceSecurityGroup
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          # Update the package index
          yum update -y
          
          # Install Git, Python3, and pip
          yum install -y git python3 python3-pip
          
          # Clone the specific branch from the GitHub repository
          git clone -b Updates_for_OH --single-branch https://github.com/tedmanlacy/smartStructsAPI.git /home/ec2-user/myfastapiapp
          
          # Navigate to the application directory
          cd /home/ec2-user/myfastapiapp
          
          # Install the required Python packages
          pip install -r requirements.txt
          pip install uvicorn
          pip install fastapi   
          
          yum install -y awslogs
          cat <<EOF > /etc/awslogs/awslogs.conf
          [general]
          state_file = /var/lib/awslogs/agent-state

          [/var/log/messages]
          file = /var/log/messages
          log_group_name = MyEC2LogGroup
          log_stream_name = {instance_id}/messages
          datetime_format = %b %d %H:%M:%S
          EOF

          service awslogs start
          chkconfig awslogs on
          
          # Start the FastAPI app with Uvicorn and log output
          nohup uvicorn main:app --host 0.0.0.0 --port 80 > /var/log/myfastapiapp.log 2>&1 &
  
  InstanceSecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: Enable SSH and HTTP access
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
  MyLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: my-log-group
      RetentionInDays: 7
Outputs:
  InstanceId:
    Description: The Instance ID
    Value: !Ref EC2Instance
  PublicIP:
    Description: Public IP address of the EC2 instance
    Value: !GetAtt EC2Instance.PublicIp