AWSTemplateFormatVersion: '2010-09-09'
Description: CloudFormation Template to deploy smartStructsAPI to an EC2 instance

Resources:
  EC2Instance:
    Type: 'AWS::EC2::Instance'
    Properties:
      InstanceType: t2.micro
      KeyName: ss_OH_API
      ImageId: ami-06b21ccaeff8cd686 # Amazon Linux 2 AMI
      SecurityGroups:
        - !Ref InstanceSecurityGroup
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          yum update -y
          yum install -y git
          yum install -y docker
          service docker start
          usermod -a -G docker ec2-user
          git clone https://github.com/tedmanlacy/smartStructsAPI.git /home/ec2-user/smartStructsAPI
          cd /home/ec2-user/smartStructsAPI
          docker build -t smartstructsapi .
          docker run -d -p 80:80 smartstructsapi

  InstanceSecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: Enable SSH and HTTP access
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0

Outputs:
  InstanceId:
    Description: The Instance ID
    Value: !Ref EC2Instance
  PublicIP:
    Description: Public IP address of the EC2 instance
    Value: !GetAtt EC2Instance.PublicIp